Feature/hounslow ch290 create service eligibility taxonomies
One-Hounslow-Connect/api pull request #55
Opened 2021-05-18 15:00 UTC by fred-aghq

### Summary

https://app.clubhouse.io/ayup-digital-ltd/story/290/create-service-eligibility-taxonomies

Adds a migration that will add Service Eligibility as a top-level Taxonomy item, ready for importing the associated Service Eligibility child taxonomies.

The full CSV for the child taxonomies can be found here (requires Clubhouse access): https://media.clubhouse.io/api/attachments/files/clubhouse-assets/606c8274-5319-4fe9-a210-3ea7c712b38e/60a3d4c6-ddf2-4d27-9943-3664ba11ff1e/service_eligibility_taxonomies.csv

### Development checklist

- [ ] Changes have been made to the API?
  - [ ] If so, the OpenAPI specification has been updated
- [x] Database migrations have been added?
  - [ ] If so, the MySQL Workbench ERD has been updated - N/A - adding data, not changing schema
- [x] The code has been linted `./develop composer fix:style`

### Release checklist

Run migrations.
CSV file is available here: https://media.clubhouse.io/api/attachments/files/clubhouse-assets/606c8274-5319-4fe9-a210-3ea7c712b38e/60a3d4c6-ddf2-4d27-9943-3664ba11ff1e/service_eligibility_taxonomies.csv

2021-05-18 15:01 UTC, fred-aghq commented on database/migrations/2021_05_18_144245_seed_service_eligibility_parent_category.php
> +class SeedServiceEligibilityParentCategory extends Migration
I was _tempted_ to make this an (abstract) class from which a migration could be extended, but that felt like over-engineering. depends how much we expect to add new taxonomies in the future.

2021-05-19 08:36 UTC, appsol commented on database/migrations/2021_05_18_144245_seed_service_eligibility_parent_category.php
> +class SeedServiceEligibilityParentCategory extends Migration
You are correct, that would be over-engineered. This is the 3rd root taxonomy to be added, and the first in some time, so this is not something we expect to happen often.

2021-05-19 08:39 UTC, appsol commented on storage/app/service-eligibility/taxonomy.json
> +    "order": 1,
Should be order: 0. Order is 0 indexed.

2021-05-19 08:40 UTC, appsol commented on storage/app/service-eligibility/taxonomy.json
> +    "depth": 1
Should be depth: 0 as it does not have a parent ID.

2021-05-19 08:42 UTC, appsol requested changes
Alter root category to depth: 0 and order: 0.

2021-05-19 08:43 UTC, fred-aghq commented on storage/app/service-eligibility/taxonomy.json
> +    "depth": 1
On it.

2021-05-19 10:01 UTC, merged