Feature/hounslow ch302 use eligibility types for criteria in api
One-Hounslow-Connect/api pull request #58
Opened 2021-05-21 12:59 UTC by fred-aghq

### Summary

https://app.clubhouse.io/ayup-digital-ltd/story/302/use-eligibility-types-for-criteria-in-api-response

### Development checklist

- [ ] Changes have been made to the API?
  - [ ] If so, the OpenAPI specification has been updated
- [ ] Database migrations have been added?
  - [ ] If so, the MySQL Workbench ERD has been updated
- [x] The code has been linted `./develop composer fix:style`

2021-05-21 13:51 UTC, appsol commented on app/Http/Resources/ServiceCriterionResource.php
>      }
Could this all not have been done cleaner with mutators? https://laravel.com/docs/5.8/eloquent-mutators

2021-05-21 13:55 UTC, appsol commented on app/Models/Service.php
>  }
Could be created as an Accessor https://laravel.com/docs/5.8/eloquent-mutators#defining-an-accessor

2021-05-21 13:56 UTC, appsol commented on database/migrations/2021_05_19_100456_add_custom_eligibility_type_fields_to_services.php
> +}
Is this nor in PR#57?

2021-05-21 14:51 UTC, appsol requested changes
I'm not sure we're on the right track with this.
Are we not just replicating the service taxonomy relationships with another name? The pivot table is the same and the relationships are the same. The only difference between a category and a service_eligibility is the root taxonomy, otherwise they are identical.
I think we need to look at #300, #301 and #302 again, remembering that these are just taxonomies, so can use the existing taxonomy functionality. The only change is with the custom fields, which can be managed via accessors that check whether taxonomy relationships exist or custom fields are populated, or both.

2021-05-24 09:49 UTC, fred-aghq commented on app/Http/Resources/ServiceCriterionResource.php
>      }
As discussed outside of github, I think this would be prudent to refactor during the work for CH-303 :) I've made a note.

2021-05-24 09:55 UTC, fred-aghq commented on database/migrations/2021_05_19_100456_add_custom_eligibility_type_fields_to_services.php
> +}
Yes but I needed it for this work too :) merging PR#57 first

2021-05-24 10:14 UTC, merged