Feature/hounslow ch303 manage eligibility types
One-Hounslow-Connect/api pull request #66
Opened 2021-05-27 14:21 UTC by fred-aghq

### Summary

https://app.clubhouse.io/ayup-digital-ltd/story/303/manage-eligibility-types

Write a brief short summary about the PR here.

### Development checklist

- [x] Changes have been made to the API?
  - [ ] If so, the OpenAPI specification has been updated
- [x] Database migrations have been added?
  - [ ] If so, the MySQL Workbench ERD has been updated
- [x] The code has been linted `./develop composer fix:style`

### Release checklist

If there are any actions that must be performed as part of the release, then
create a checklist for them here.

### Notes

If there are any further notes about the PR then write them here.

2021-05-27 16:18 UTC, appsol commented on app/Http/Requests/Service/UpdateRequest.php
> +
As we will only accept specific keys on the `eligibility_types.custom` object, it might be better to set them out specifically:

```suggestion
'eligibility_types.custom' => ['array'],
'eligibility_types.age_group' => ['nullable', 'string', 'min:1', 'max:255'],
'eligibility_types.disability' => ['nullable', 'string', 'min:1', 'max:255'],
'eligibility_types.employment' => ['nullable', 'string', 'min:1', 'max:255'],
'eligibility_types.gender' => ['nullable', 'string', 'min:1', 'max:255'],
'eligibility_types.housing' => ['nullable', 'string', 'min:1', 'max:255'],
'eligibility_types.income' => ['nullable', 'string', 'min:1', 'max:255'],
'eligibility_types.language' => ['nullable', 'string', 'min:1', 'max:255'],
```

2021-05-27 16:42 UTC, appsol commented on app/Models/Mutators/ServiceMutators.php
> +            ->each(function ($item) use (&$keyedByName) {
MapWithKeys might have been a bit neater https://laravel.com/docs/5.8/collections#method-mapwithkeys

2021-05-27 16:45 UTC, appsol commented on app/Models/Service.php
> +                    if (!in_array($fieldName, ServiceTaxonomy::SUPPORTED_CUSTOM_FIELD_NAMES)) {
This should form part of the validation. You should be confident in your data by this point.

2021-05-27 16:50 UTC, appsol commented on app/Services/DataPersistence/ServicePersistenceService.php
> +                        continue;
Should be in validation

2021-05-27 16:52 UTC, appsol commented on app/Services/DataPersistence/ServicePersistenceService.php
> +            if ($request->has('eligibility_types.taxonomies') && !empty($request->eligibility_types['taxonomies'])) {
Use `$request->filled()` does the same.

2021-05-27 16:56 UTC, appsol commented on app/Services/DataPersistence/ServicePersistenceService.php
> +                        : new MissingValue(),
Would `$request->input('eligibility_types.taxonomies', (new MissingValue()))` work here?

2021-05-27 18:02 UTC, fred-aghq reviewed
I can't request changes on my own PR, but @appsol please feel free to weigh in on the comments I've left in addition to your own comments :)

2021-05-28 08:36 UTC, appsol commented on tests/Feature/TaxonomyServiceEligibilityTest.php
> +        $this->assertEquals($ageGroupCustom, $updateRequestData['eligibility_types']['custom']['age_group']);
You could try:
`$this->assertJsonStringEqualsJsonString(json_encode($payload), json_encode($updateRequestData));`
or
`$this->assertArraySubset($payload, $updateRequestData);`

2021-05-28 08:39 UTC, appsol commented on tests/Feature/TaxonomyServiceEligibilityTest.php
> +        $this->assertEquals($ageGroupCustom, $updateRequestData['eligibility_types']['custom']['age_group']);
Also worth thinking about splitting the tests up. The creation of the update request should be a feature test as it is driven by the controller, but lots of the internal workings, including the applying of the update request could be better tested via integration or unit tests that look at the functionality of the individual methods.

2021-05-28 08:42 UTC, appsol requested changes
Good work, looks fine overall. I've added some comments around a few things you should look at, nothing major. I'll request changes just to let you fix these.

2021-05-28 09:20 UTC, fred-aghq commented on app/Models/Mutators/ServiceMutators.php
> +            ->each(function ($item) use (&$keyedByName) {
I thought this too, but couldn't get my head around it at the time xD

2021-05-28 09:35 UTC, appsol requested changes
I've just noticed the Docs have not been updated to match the changes to the API. This will need to be implemented before the PR can be accepted.

2021-05-28 10:05 UTC, fred-aghq commented on app/Http/Requests/Service/UpdateRequest.php
> +
Done.

2021-05-28 10:07 UTC, appsol requested changes
Sorry, found another thing.
You have no Feature tests to look for `eligibility_types` in any responses. Not sure how some of the tests are passing TBH?

2021-05-28 11:07 UTC, fred-aghq commented on app/Models/Mutators/ServiceMutators.php
> +            ->each(function ($item) use (&$keyedByName) {
I agree fully with this comment, but I'm going to leave it for now if that's ok?

2021-05-28 11:22 UTC, fred-aghq commented on app/Services/DataPersistence/ServicePersistenceService.php
> +                        : new MissingValue(),
Using a default value combined with `input()` is much cleaner, thank you :)

2021-06-01 15:29 UTC, fred-aghq commented
Closing as new PR to be raised with refactor/fixes

2021-06-01 15:29 UTC, closed without merging