Feature/hounslow ch303 manage eligibility types refactor
One-Hounslow-Connect/api pull request #67
Opened 2021-06-01 00:26 UTC by fred-aghq

### Summary

https://paste-trello-link-here

Write a brief short summary about the PR here.

### Development checklist

- [ ] Changes have been made to the API?
  - [ ] If so, the OpenAPI specification has been updated
- [ ] Database migrations have been added?
  - [ ] If so, the MySQL Workbench ERD has been updated
- [ ] The code has been linted `./develop composer fix:style`

### Release checklist

If there are any actions that must be performed as part of the release, then
create a checklist for them here.

### Notes

If there are any further notes about the PR then write them here.

2021-06-01 00:27 UTC, fred-aghq commented on app/Docs/Schemas/Service/ServiceSchema.php
> +                    ->nullable(),
Schema needs updating/finishing

2021-06-01 00:29 UTC, fred-aghq commented on app/Models/ServiceEligibility.php
> +    const SUPPORTED_CUSTOM_FIELD_NAMES = [
remove this, unneccessary

2021-06-01 09:42 UTC, fred-aghq commented
- Integration tests - particularly update - Update Request created, check database has updated entity post-approval 
- finish schema definitions

2021-06-02 11:40 UTC, appsol commented on app/Models/Service.php
> +
Are you setting all the `eligibility_customtype_custom` fields again here?
These are already set starting at line 246.

2021-06-02 11:41 UTC, appsol commented on app/Models/Service.php
> +            }
This will only save the model if the `$data['eligibility_types']['custom']` filed is set. Is that the intended outcome?

2021-06-02 11:48 UTC, appsol commented on app/Services/DataPersistence/ServicePersistenceService.php
> +
Should have been done as part of the initial Service::create, as the service is not persisted after this.

2021-06-02 11:50 UTC, appsol commented on app/TaxonomyRelationships/UpdateServiceEligibilityTaxonomyRelationships.php
> +        return $this->serviceEligibilities()->updateOrCreate(['taxonomy_id' => $taxonomy->id]);
Does not need to be updateOrCreate as you have just deleted all of them. Just create will be fine, which means you can pass an array and do it in 1 db call rather than potentially hundreds.

2021-06-02 11:54 UTC, appsol requested changes
Much better, makes much more sense now. Please see the individual comments.

2021-06-02 12:43 UTC, fred-aghq commented on app/TaxonomyRelationships/UpdateServiceEligibilityTaxonomyRelationships.php
> +        return $this->serviceEligibilities()->updateOrCreate(['taxonomy_id' => $taxonomy->id]);
strange, i swear i copied the existing taxonomy relationship class

2021-06-02 13:13 UTC, appsol approved these changes
Nicely done.

2021-06-02 13:24 UTC, merged