Feature/hounslow ch440 add eligibility to search
One-Hounslow-Connect/api pull request #71
Opened 2021-06-10 14:38 UTC by fred-aghq

### Summary

https://app.clubhouse.io/ayup-digital-ltd/story/440/add-eligibility-to-search

Write a brief short summary about the PR here.

### Development checklist

- [x] Changes have been made to the API?
  - [x] If so, the OpenAPI specification has been updated
- [ ] Database migrations have been added?
  - [ ] If so, the MySQL Workbench ERD has been updated
- [x] The code has been linted `./develop composer fix:style`

2021-06-10 16:08 UTC, fred-aghq commented on app/Docs/Schemas/Search/StoreSearchSchema.php
> +                Schema::array('service_elgibilities')
typo!

2021-06-11 15:58 UTC, appsol commented on app/Models/Service.php
> +    }
Do we still need this?
If not better removed.

2021-06-11 16:03 UTC, appsol commented on app/Search/ElasticsearchSearch.php
> +
By writing over the whole query object, are you not preventing a combination query? e.g. Search for Age 12-15 + is free + within geo area?

2021-06-11 16:05 UTC, appsol commented on tests/Feature/SearchTest.php
> +    }
Would be good to have 1 test that is a combo of multiple search terms, not worried about what it brings back (too hard to predict) so long as it's 200.

2021-06-11 16:05 UTC, appsol requested changes
See individual comments.

2021-06-13 10:44 UTC, fred-aghq commented on app/Models/Service.php
> +    }
I agree, however at the moment it is still used by the ServiceEligibilityResource within ServiceResource.

I'll look at refactoring once I've addressed the more urgent issues.

2021-06-14 16:07 UTC, appsol approved these changes
Looks good.

2021-06-14 16:15 UTC, merged